#include <stdio.h>
#define A (
#define AA )
#define AAA {
#define AAAA }
#define AAAAAA ;
#define AAAAAAA int
#define AAAAAAAA void
#define AAAAAAAAA main
#define AAAAAAAAAA for
#define AAAAAAAAAAA i
#define AAAAAAAAAAAA =
#define AAAAAAAAAAAAA 0
#define AAAAAAAAAAAAAA <
#define AAAAAAAAAAAAAAA 10
#define AAAAAAAAAAAAAAAA ++
#define AAAAAAAAAAAAAAAAA printf
#define AAAAAAAAAAAAAAAAAA "A"
#define AAAAAAAAAAAAAAAAAAA "\n"
#define AAAAAAAAAAAAAAAAAAAA return

AAAAAAA AAAAAAAAA A AAAAAAAA AA AAA
    AAAAAAAAAA A AAAAAAA AAAAAAAAAAA AAAAAAAAAAAA AAAAAAAAAAAAA AAAAAA AAAAAAAAAAA AAAAAAAAAAAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAA AAAAAAAAAAAAAAAA AA AAA
        AAAAAAAAAAAAAAAAA A AAAAAAAAAAAAAAAAAA AA AAAAAA
    AAAA
    AAAAAAAAAAAAAAAAA A AAAAAAAAAAAAAAAAAAA AA AAAAAA
    AAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAA AAAAAA
AAAA
